### ISSUE TITLE
1.19 Unsupported

### ISSUE THREAD

**Issue by lightumcc** [Sportkanone123/ClientDetector#12]
**General Information**
Server version: paper-1.19-28
Server software: paper
Client version:  1.19
Client software: Fabric
Plugin version: 2.4.9

**Describe the bug**
If I enable the Client Detector, player cannot enter the server

**To Reproduce**
Go to papermc.io to download the latest paper server
Install the CD
Let a player enter the server by using any version in 1.19
You will see the error

(Sorry, my mother language is not English, if you cannot understand my sentences, please comment this issue)

**Comment by Sportkanone123** [comment]
Hey, ClientDetector does not yet support 1.19 because PacketEvents has not yet added compatibility for 1.19
~Sportkanone123

**Comment by lightumcc** [comment]
Thanks a lot!
