### ISSUE TITLE
Add OptiFine as a blacklistable "client" (even if it's not)

### ISSUE THREAD

**Issue by craftish37** [Sportkanone123/ClientDetector#14]
OptiFine causes some troubles with ticking other clients/server and ressourcepack issues on some servers, maybe it could be preferable to add it as a blacklistable "client" (I already tried, can't find an idea of how to process)

**Comment by Sportkanone123** [comment]
The problem is optifine is not really detectable, just FastMath can be detected in certain situations.
~Sportkanone123

**Comment by craftish37** [comment]
For the FastMath thing, I found a [cool base](https://github.com/MWHunter/AntiFastMath) who kinda just need to be updated, maybe it's perfectible by checking what FastMath is changing, which I don't know much appart from reach sometimes, ticking and render issues

**Comment by Sportkanone123** [comment]
https://github.com/Sportkanone123/ClientDetector/blob/master/src/main/java/de/sportkanone123/clientdetector/spigot/hackdetector/impl/AntiFastMath.java
AntiFastMath is already based on https://github.com/MWHunter/AntiFastMath. Check the credits.
