### ISSUE TITLE
Add the ability to blacklist certain players

### ISSUE THREAD

**Issue by FireController1847** [Sportkanone123/ClientDetector#18]
**Your suggestion/idea.**
Essentially, the opposite of the "whitelist players," instead of _whitelisting_ players who get checked, we should instead _blacklist_ players who get checked. Thereby, we can kick players who join with modded clients who are known for abusing this, but still allowing them to join the server with vanilla clients :)

**Comment by Sportkanone123** [comment]
Just add a punishments to all clients except vanilla.
