### ISSUE TITLE
Schematica

### ISSUE THREAD

**Issue by ga6rielsilva** [Sportkanone123/ClientDetector#21]
**Your suggestion/idea.**
A clear and concise description of your idea and why it should be added to ClientDetector.

Add Schematica mod (or similar ones like Litematica) to the list of mods that can be blocked from, as it can be used in the same way as WDL

https://www.curseforge.com/minecraft/mc-mods/schematica
https://www.curseforge.com/minecraft/mc-mods/litematica

**Comment by Sportkanone123** [comment]
Sorry but this is technically not possible at the moment.

**Comment by ga6rielsilva** [comment]
@Loving11ish
