### ISSUE TITLE
Console Error on 1.19.2 join

### ISSUE THREAD

**Issue by Chris6ix** [Sportkanone123/ClientDetector#22]
**General Information**
Server version:  Paper 1.19.2
Client version:  Fabric 1.19.2
Plugin version: 2.5.3

**Describe the bug**
When joining my 1.19.2 Paper Server, I see this error in my console, even with ClientDetector 2.5.3

![image](https://user-images.githubusercontent.com/65610536/185967644-ba18eb5d-adec-45c2-a5b7-37ac5be2c3e8.png)

**To Reproduce**
Join a 1.19.2 Server with ClientDetector installed?

**Comment by Sportkanone123** [comment]
This is an issue with PacketEvents. I will update the dependency and we will see how it works out.

**Comment by Loving11ish** [comment]
I have taken over development of ClientDetector, is this issue still persisting @Chris6ix  or can I close this issue?

**Comment by Chris6ix** [comment]
I don't know. I have stopped using ClientDetector because it was either barely working or not at all and broke more with every MC update.
I am also currently not planning to use ClientDetector again, so you can close this issue.

Thank you though for asking.
