### ISSUE TITLE
1.19 PacketEvents caught an unhandled exception while calling your listener.ntDetector.jar:?] Error

### ISSUE THREAD

**Issue by Tapimur** [Sportkanone123/ClientDetector#24]
https://pastebin.com/7014kCs6

General Information
Server version: (e.g.: purpur-1.19-1735)
Client version: (e.g.: Vanilla/Fabric/Forge/ 1.19)
Plugin version: (e.g.: 2.5) (I have tried other 1.19 versions and they all face the same error)

When I log in with Fabric or hack client, this error appears, normally it should kick from the server

**Comment by Sportkanone123** [comment]
Does the issue still occur, if yes can you send me the error with the newest version.

**Comment by VincentX0905** [comment]
i got same error
> https://pastebin.com/dF350HSW

```
Server version: purpur-1.19-1838
Client version: Fabric V1.19.2
Plugin version: 2.5.3
```

**Comment by Sportkanone123** [comment]
This is an issue with PacketEvents. I will update the dependency and we will see how it works out.

**Comment by Loving11ish** [comment]
I have taken over development of ClientDetector, is this issue still persisting @vincentwang0905  or can I close this issue?

**Comment by VincentX0905** [comment]
Yes Fixed @Loving11ish 
It working fine
