### ISSUE TITLE
Incompatible with 1.19.4

### ISSUE THREAD

**Issue by Calvineries** [Sportkanone123/ClientDetector#29]
**General Information**
Server version: Paper 1.19.4
Client version: Fabric or Vanilla 1.19.4
Plugin version: 2.5.4

**Describe the bug**
When someone want to connect:
```Player lost connection: Internal Exception: io.netty.handler.codec.EncoderException: de.sportkanone123.clientdetector.spigot.packetevents.exception.PacketProcessException: Failed to map the Packet ID 109 to a PacketType constant. Bound: CLIENT, Connection state: PLAY, Server version: 1.19.3```

**Comment by Loving11ish** [comment]
I have taken over development of ClientDetector, is this issue still persisting @Calvineries or can I close this issue?

**Comment by Calvineries** [comment]
Issue has been fixed in 2.5.5.
Thanks.
