### ISSUE TITLE
Using any forge MC version (1.8.8-1.17.1), forge isn't blocked

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [Sportkanone123/ClientDetector#3]
the title says it all
i made sure that "blockForge" is true in the config

**Comment by Sportkanone123** [comment]
Hey there,
Forge should be blocked on all versions, but Modlist detection has some limitations. Can you tell me what forge version is not detected and the version of the server you are using?
~Sportkanone123

**Comment by MotikaCraft-TheJoshua** [comment]
Forge client version (1.12.2)
![image](https://user-images.githubusercontent.com/56804505/136445704-435eca48-e570-4062-8df5-dccd0344bebb.png)

Server version (paper 1.12.2)
![image](https://user-images.githubusercontent.com/56804505/136445731-8a78d71a-f0cc-4f8b-928a-c07db1ad92eb.png)

Plugin version
![image](https://user-images.githubusercontent.com/56804505/136445776-4c6f611e-1433-4220-8ac5-90b1dbc76644.png)

**Comment by Sportkanone123** [comment]
Okay, thats strange I will look into it tomorrow (german time).

**Comment by MotikaCraft-TheJoshua** [comment]
No worries, i can help you with testing anything, we can text on discord if you'd like
TheJoshua#3924
