### ISSUE TITLE
Re-logging does not disable Lunar options

### ISSUE THREAD

**Issue by cobrex1** [Sportkanone123/ClientDetector#6]
Waterfall Network release 474, 475 and 477
Paper servers 1.18.1 release 100 to 186
Plugin version 2.4.5 and 2.4.6

When a client is first booted up and joins the network Lunar options are disabled as per my config settings. Moving between the backend servers the Lunar options are still disabled, however, if the client disconnects from the network and re-joins without restarting the client all Lunar options are enabled again.

On disconnecting and restarting the client, then re-joining the network the options listed in the config are disabled.

I have tested this with a non-op'ed player

**Comment by Sportkanone123** [comment]
Hey thee, this is a known issue. However I have not found a fix for it. The weird thing is that the client receives the blacklisted mods nevertheless they still work. And also the official Lunar (Bukkit) API does not work (same issue). We will have to wait until the Lunar Dev's fix the issue.
~Sportkanone123

**Comment by cobrex1** [comment]
Thanks for the quick response. Well we have to wait for them which is most unfortunate as I know they are not the most prompt at dealing/helping.

**Comment by Sportkanone123** [comment]
Issue has been resolved by the Lunar Client Team. Disabling Lunar mods should now be working fine.
~Sportkanone123
