### ISSUE TITLE
Players cannot join the game

### ISSUE THREAD

**Issue by AdminHcat** [Sportkanone123/ClientDetector#7]
**General Information**
Server version:  ... (e.g.: 1.17.1) 1.18.1
Server software: ... (e.g.: Paper/Spigot/Bukkit)
Client version:  ... (e.g.: 1.17.1) 1.18.1
Client software: ... (e.g.: Vanilla/Lunar/Badlion/Forge)
Plugin version: ... (e.g.: 2.2.5) 2.4.6

**Describe the bug**
Player cannot join the game prompt ：
xxxplayer lost connection: Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 2 is below server threshold of 512

After repeated screening, this is the problem of this plugin
My player has been kicked repeatedly in server

**To Reproduce**

**Comment by Sportkanone123** [comment]
Hey there, for now there is only one solution to your problem, disable 'forge.simulateForgeHandshake' in config.yml.
~Sportkanone123
