### ISSUE TITLE
More/Better Fabric Mods detection

### ISSUE THREAD

**Issue by Chris6ix** [Sportkanone123/ClientDetector#9]
**Your suggestion/idea.**
Hey, I really love the idea of this plugin, but when I tested it with my modded Fabric client, it detected none of the mods I was using (When doing `/mods Chris6ix` it returned `Chris6ixˈs mods:` without anything after that :/ )
It only detected that I'm using Fabric on 1.18

**Comment by Sportkanone123** [comment]
Hey there, unfortunately for fabric that's normal, It is not possible to get the modlist from the client. There are only some mods detected on Fabric which are detectable with other methods.
~Sportkanone123

**Comment by Chris6ix** [comment]
Oh...that is very unfortunate :/
That sadly makes the plugin a bit unusable for me, as a lot of my Players use Fabric

I have sent a small PR (#8)  tho, to help improve the plugin a little, as I really love the idea :)
Thanks for your fast response tho :)
